const emojiStory = document.getElementById("emojiStory");
const generateBtn = document.getElementById("generateBtn");

generateBtn.addEventListener("click", function () {
  const sentence = document.getElementById("sentence").value;
  const emojiSentence = convertToEmoji(sentence);
  emojiStory.textContent = emojiSentence;
});

function convertToEmoji(sentence) {
  const emojiMap = {
    //Pronouns
    i: "👤",
    you: "👉",
    he: "👨",
    she: "👩",
    it: "🤖",
    we: "👥",
    they: "👥",
    me: "🙋‍♂️",
    him: "🙋‍♂️",
    her: "🙋‍♀️",
    us: "👫",
    them: "👫",
    my: "👤",
    your: "👉",
    his: "👨",
    her: "👩",
    its: "🤖",
    our: "👥",
    their: "👥",
    mine: "🙋‍♂️",
    yours: "👉",
    hers: "🙋‍♀️",
    ours: "👫",
    theirs: "👫",

    //person
    girl: "👧",
    boy: "👦",

    happy: "😄",
    love: "❤️",
    sad: "😢",
    angry: "😡",
    surprised: "😮",
    laugh: "😂",
    cry: "😭",
    heart: "💖",
    "thumbs up": "👍",
    "thumbs down": "👎",
    rocket: "🚀",
    unicorn: "🦄",
    cake: "🍰",
    coffee: "☕",
    sun: "☀️",
    moon: "🌙",
    star: "⭐",
    rainbow: "🌈",
    hi: "👋",
    dog: "🐶",
    cat: "🐱",
    flower: "🌸",
    tree: "🌳",
    pizza: "🍕",
    burger: "🍔",
    "ice cream": "🍦",
    soccer: "⚽",
    basketball: "🏀",
    guitar: "🎸",
    book: "📚",
    film: "🎬",
    music: "🎵",
    fire: "🔥",
    water: "💧",
    earth: "🌍",
    airplane: "✈️",
    train: "🚂",
    car: "🚗",
    bicycle: "🚲",
    boat: "⛵",
    house: "🏠",
    school: "🏫",
    hospital: "🏥",
    "love letter": "💌",
    money: "💰",
    party: "🎉",
    sleep: "😴",
    yawn: "😪",
    smile: "😊",
    wink: "😉",
    cool: "😎",
    nerd: "🤓",
    hug: "🤗",
    kiss: "💋",
    thinking: "🤔",
    clap: "👏",
    handshake: "🤝",
    shhh: "🤫",
    ghost: "👻",
    alien: "👽",
    skull: "💀",
    robot: "🤖",
    sunglasses: "😎",
    umbrella: "☂️",
    tornado: "🌪️",
    snowman: "⛄",
    lightning: "⚡",
    thunder: "🌩️",
    rain: "🌧️",
    cloud: "☁️",
    wind: "🌬️",
    fog: "🌫️",
    rainbow: "🌈",
    stars: "🌟",
    cloudy: "⛅",
    sunrise: "🌅",
    sunset: "🌇",
    night: "🌃",
    cityscape: "🌆",
    mountain: "⛰️",
    volcano: "🌋",
    beach: "🏖️",
    desert: "🏜️",
    island: "🏝️",
    park: "🏞️",
    forest: "🌳",
    camping: "🏕️",
    tent: "⛺",
    house: "🏠",
    building: "🏢",
    office: "🏬",
    "post office": "🏤",
    bank: "🏦",
    hospital: "🏥",
    school: "🏫",
    university: "🏛️",
    hotel: "🏨",
    motel: "🏩",
    "love hotel": "🏩",
    wedding: "💒",
    church: "⛪",
    mosque: "🕌",
    synagogue: "🕍",
    temple: "🛕",
    shrine: "⛩️",
    "house with garden": "🏡",
    cityscape: "🌆",
    "cityscape at night": "🌃",
    bridge: "🌉",
    "ferris wheel": "🎡",
    "roller coaster": "🎢",
    "carousel horse": "🎠",
    castle: "🏰",
    "statue of liberty": "🗽",
    pyramid: "🏰",
    museum: "🏰",
    fountain: "⛲",
    tent: "⛺",
    "shopping bags": "🛍️",
    balloon: "🎈",
    flags: "🎏",
    ribbon: "🎀",
    gift: "🎁",
    "confetti ball": "🎊",
    "party popper": "🎉",
    fireworks: "🎆",
    sparkler: "🎇",
    "wind chime": "🎐",
    bell: "🔔",
    "musical note": "🎵",
    "musical notes": "🎶",
    "studio microphone": "🎙️",
    "level slider": "🎚️",
    "control knobs": "🎛️",
    microphone: "🎤",
    headphones: "🎧",
    radio: "📻",
    saxophone: "🎷",
    guitar: "🎸",
    "musical keyboard": "🎹",
    trumpet: "🎺",
    violin: "🎻",
    drum: "🥁",
    iphone: "📱",
    calling: "📲",
    telephone: "☎️",
    "fax machine": "📠",
    battery: "🔋",
    "electric plug": "🔌",
    laptop: "💻",
    computer: "🖥️",
    "desktop computer": "🖥️",
    printer: "🖨️",
    keyboard: "⌨️",
    "computer mouse": "🖱️",
    trackball: "🖲️",
    "flash drive": "🖲",
    "satellite antenna": "📡",
    television: "📺",
    camera: "📷",
    "video camera": "📹",
    "movie camera": "🎥",
    "film projector": "📽️",
    "video game": "🎮",
    joystick: "🕹️",
    "slot machine": "🎰",
    keyboard: "⌨️",
    "computer mouse": "🖱️",
    trackball: "🖲️",
    candle: "🕯️",
    "light bulb": "💡",
    flashlight: "🔦",
    battery: "🔋",
    "electric plug": "🔌",
    lamp: "🪔",
    "desktop computer": "🖥️",
    printer: "🖨️",
    "computer disk": "💽",
    "floppy disk": "💾",
    "optical disk": "💿",
    dvd: "📀",
    abacus: "🧮",
    calculator: "🧮",
    briefcase: "💼",
    "file cabinet": "🗄️",
    clipboard: "📋",
    paperclip: "📎",
    notebook: "📓",
    calendar: "📅",
    "spiral calendar": "🗓️",
    "card index": "📇",
    chart: "📈",
    "bar chart": "📊",
    "telephone receiver": "📞",
    pager: "📟",
    "fax machine": "📠",
    tv: "📺",
    radio: "📻",
    "studio microphone": "🎙️",
    "level slider": "🎚️",
    "control knobs": "🎛️",
    stopwatch: "⏱️",
    "timer clock": "⏲️",
    "alarm clock": "⏰",
    "mantelpiece clock": "🕰️",
    hourglass: "⏳",
    "hourglass done": "⌛",
    watch: "⌚",
    satellite: "🛰️",
    "satellite antenna": "📡",
    syringe: "💉",
    pill: "💊",
    microscope: "🔬",
    telescope: "🔭",
    dna: "🧬",
    microbe: "🦠",
    "petri dish": "🧫",
    "test tube": "🧪",
    thermometer: "🌡️",
    broom: "🧹",
    basket: "🧺",
    "roll of paper": "🧻",
    "toilet paper": "🧻",
    soap: "🧼",
    sponge: "🧽",
    "fire extinguisher": "🧯",
    "shopping cart": "🛒",
    smoking: "🚬",
    coffin: "⚰️",
    headstone: "🪦",
    "funeral urn": "⚱️",
    moyai: "🗿",
    placard: "🪧",
    atm: "🏧",
    restroom: "🚻",
    want: "🤩",
    go: "🚶‍♂️",
    run: "🏃‍♂️",
    eat: "🍽️",
    drink: "🍹",
    sleep: "😴",
    "wake up": "⏰",
    dance: "💃",
    sing: "🎤",
    laugh: "😂",
    cry: "😭",
    smile: "😊",
    frown: "☹️",
    think: "🤔",
    dream: "💭",
    work: "💼",
    study: "📚",
    play: "🎮",
    read: "📖",
    write: "📝",
    listen: "👂",
    speak: "🗣️",
    see: "👀",
    watch: "📺",
    create: "🎨",
    explore: "🔍",
    travel: "✈️",
    learn: "🎓",
    teach: "👩‍🏫",
    help: "🤝",
    love: "❤️",
    hate: "💔",
    hope: "🙏",
    wish: "🌠",
    believe: "🙌",
    try: "👍",
    fail: "😞",
    succeed: "🎉",
    accept: "✅",
    reject: "❌",
  };

  const phrases = sentence.match(/\b\w+\b/g);
  let emojiSentence = "";

  if (phrases) {
    phrases.forEach((phrase) => {
      const cleanPhrase = phrase.toLowerCase().replace(/[^\w\s]/g, "");
      if (emojiMap[cleanPhrase]) {
        emojiSentence += emojiMap[cleanPhrase] + " ";
      } else {
        emojiSentence += phrase + " ";
      }
    });
  }

  return emojiSentence.trim();
}
